version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development

  database:
    image: postgres:12.1
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server

  sidekiq:
    build:
      context: .
    depends_on:
      - app
      - database
      - redis
    volumes:
      - .:/app
    command: bundle exec sidekiq
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  db_data:
